### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by moarliman** [Cast39/MQTT_Device_Controls#2]
Hi, love the app. It's exactly what I was looking for. Could you please provide some documentation. I'm especially interested in how to create a toggle with slider and how to get the states of the buttons in sync.

**Comment by Cast39** [comment]
Hey, thanks for your appreciation. Unfortunately your requested features aren't implemented yet. For now I've copied the example config in the readme file. The documentation might take some time, do you have a specific information you're missing?

**Comment by moarliman** [comment]
I just saw in your code, that these features aren't ready yet. Most
important would be to not lose the state of the button, or even better,
keep it up to date via mqtt. Is that possible? When I close and open the
device control, everything is off.

**Comment by Cast39** [comment]
Ah yes, over retained messages could work. Not sure how tho, it's been 2yrs when I last looked at the code. If I remember correctly, I've only used functions, which will be executed, when a button is pressed or a slider is changed, so that'd need to be fixed

**Comment by Cast39** [comment]
Hey, I've got it now, the Devicecontrols will now be updated if a message gets sent at the topic, which they normally send at themselves, so if you enable the retained flag, they'll always show the current state^^
[release v1.3](https://github.com/Cast39/MQTT_Device_Controls/releases/tag/v1.3)

**Comment by moarliman** [comment]
Thanks so much! The only thing I'm missing now is the ToggleRangeTemplate 🙏

Would pay you a beer for that 🍺

**Comment by Cast39** [comment]
Ah that's very pleasant, I'll have a look at it, shouldn't be that big of a deal ;)

**Comment by Cast39** [comment]
Soo okay Toggleranges are now finally supported^^

[release v1.4](https://github.com/Cast39/MQTT_Device_Controls/releases/tag/v1.4)

**Comment by moarliman** [comment]
Awesome! Does it retain the state just on my device? Looks like it's not getting the actual state from the mqtt server. Also, where do I find a list of the available device types (number)? And where to send beer?

**Comment by Cast39** [comment]
Hey, it should get updates from the retained messages from the server, but the togglerage only supports true/false or on/off as states for now, I'm still working on checking the incoming messages with the on/offcommands.

For the available device types you can find a overview on this page: https://developer.android.com/reference/android/service/controls/DeviceTypes 

For the beer you can look at my profile, thank you ^^

**Comment by moarliman** [comment]
Would be nice to have two topics per device. One for publishing and one for subscribing the status. I'm using zigbee2mqtt. When pressing the hardware light switch the topic for setting the status doesn't get any messages. So the status on my phone is wrong. 

You should have received the beer money btw.

**Comment by Cast39** [comment]
Soo I've added the features, and also found the bug you were talking about. Have a look at the current release and the [wiki](https://github.com/Cast39/MQTT_Device_Controls/wiki)

**Comment by Cast39** [comment]
Yes, thank you very much:D I've added the features, and I think I've also found the bug you were talking about. Have a look at the current release and the [wiki](https://github.com/Cast39/MQTT_Device_Controls/wiki)
